/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-09 05:32:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Passport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Passport Registration</title>\r\n");
      out.write("\r\n");
      out.write("     <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("            background-image: url('https://img.freepik.com/free-photo/top-view-tourist-objects-frame-with-copy-space_23-2148786099.jpg?t=st=1733722115~exp=1733725715~hmac=f911e2f4cc2c6e23e0ad16f1c92da94a5ebdd5c2ce23eca3060b65e8879444c4&w=1060');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* .form-container {\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("        } */\r\n");
      out.write("\r\n");
      out.write("        h2, h3 {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control, .form-select, .form-check-input {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-info {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label{\r\n");
      out.write("            color:blue;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-check-label {\r\n");
      out.write("            color: rgb(91, 28, 208);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"form-container\">\r\n");
      out.write("        <h2>Passport Seva</h2>\r\n");
      out.write("        <h3>PSP Division</h3>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <h2>User Registration</h2>\r\n");
      out.write("        <form action=\"passport\" method=\"post\">\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label>Register to apply at*</label><br>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"applyAt\" value=\"passportOffice\" id=\"passportOffice\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"passportOffice\">Passport Office</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"applyAt\" value=\"cvpDelhi\" id=\"cvpDelhi\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"cvpDelhi\">CVP Delhi</label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"passportOffice\">Passport Office*</label>\r\n");
      out.write("                <select class=\"form-select\" name=\"passportOffice\" id=\"passportOffice\">\r\n");
      out.write("                    <option value=\"\">SELECT</option>\r\n");
      out.write("                    <option value=\"Delhi\">Delhi</option>\r\n");
      out.write("                    <option value=\"Dwarka\">Dwarka</option>\r\n");
      out.write("                    <option value=\"Mumbai\">Mumbai</option>\r\n");
      out.write("                    <option value=\"Pune\">Pune</option>\r\n");
      out.write("                    <option value=\"Chennai\">Chennai</option>\r\n");
      out.write("                    <option value=\"Coimbatore\">Coimbatore</option>\r\n");
      out.write("                    <option value=\"Bengaluru\">Bengaluru</option>\r\n");
      out.write("                    <option value=\"Mangalore\">Mangalore</option>\r\n");
      out.write("                    <option value=\"Hyderabad\">Hyderabad</option>\r\n");
      out.write("                    <option value=\"Kochi\">Kochi</option>\r\n");
      out.write("                    <option value=\"Jammu\">Jammu</option>\r\n");
      out.write("                    <option value=\"Chandigarh\">Chandigarh</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"fullName\">Given Name*</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"fullName\" id=\"fullName\" placeholder=\"First Name + Middle Name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"surName\">SurName*</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"surName\" id=\"surName\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"dob\">Date of Birth (DD/MM/YYYY)*</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"dob\" id=\"dob\" placeholder=\"DD/MM/YYYY\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"email\">Email ID*</label>\r\n");
      out.write("                <input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label>Do you want your Login ID to be the same as E-mail ID?*</label><br>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"loginIdSame\" value=\"yes\" id=\"loginYes\" required>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"loginYes\">Yes</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"loginIdSame\" value=\"no\" id=\"loginNo\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"loginNo\">No</label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"loginId\">Login ID*</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"loginId\" id=\"loginId\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"password\">Password*</label>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"confirmPassword\">Confirm Password*</label>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"confirmPassword\" id=\"confirmPassword\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-info\">Register</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
